### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Biviho** [bolderbrush10/SearchlightAssault#1]
hi, just got a crash from the mod after a bit of time playing.
it is an old save i continued playing after like 4 month, the only different thing i have done before the crash was copying a searchlight with constant combinator attached before doing other things, so i have no information on what event caused the crash

Error while running event SearchlightAssault::on_script_trigger_effect (ID 152)
Target must be entity with owner.
stack traceback:
	[C]: in function '__newindex'
	__SearchlightAssault__/control-gestalt.lua:211: in function 'EnterAlarmMode'
	__SearchlightAssault__/control-gestalt.lua:484: in function 'FoeFound'
	__SearchlightAssault__/control.lua:351: in function <__SearchlightAssault__/control.lua:344>

if you need something tell me, i'm sorry that i can't provide more specific informations

**Comment by bolderbrush10** [comment]
Thanks for your report!

I've just released version 2.0.1 to try to fix this. If it doesn't work, please send me your save game somehow, you can email me at bolderbrush10@gmail.com

The new version should start to appear in the mod portal shortly.
If you don't see it in-game you can download it manually here: https://mods.factorio.com/mod/SearchlightAssault/downloads

**Comment by Biviho** [comment]
looks like the game is not crashing anymore
