### ISSUE TITLE
control-blocklist.lua:80: attempt to index field 'boostInfo' (a nil value) on map creation

### ISSUE THREAD

**Issue by OndrejMus** [bolderbrush10/SearchlightAssault#2]
Hi, I got error on new map creation:
Error while running event SearchlightAssault::on_init()
__SearchlightAssault__/control-blocklist.lua:80: attempt to index field 'boostInfo' (a nil value)
stack traceback:
	__SearchlightAssault__/control-blocklist.lua:80: in function 'UpdateBoostInfo'
	__SearchlightAssault__/control-blocklist.lua:115: in function 'UpdateBlockList'
	__SearchlightAssault__/control-blocklist.lua:18: in function 'InitTables_Blocklist'
	__SearchlightAssault__/control-common.lua:25: in function 'InitTables'
	__SearchlightAssault__/control.lua:62: in function <__SearchlightAssault__/control.lua:60>

Map string: >>>eNp1Uj2IE0EUnrkYLpfokSL4A3qmsN0QPBUJmB1tDhHtLSebu
cvA7k6cnVVzIqa4UtHCQm1Ma2NnYXcgiIKCaCU2Zyf4g6JgI8SZ2
Z39y+XBe/nmfW/ee/NtIIDgDNA2tpUf2OMw7EYngJTLhNuPE7qk6
rDhkHCLcZKtW3J42CcWo7nbVeITb2T1cEDMCOWlARPZnhXqER5Qk
etYoZz5xTH7POoTjl3rGhaEZ5na0MU+EVZAN3OzahxzYnlEYDfI1
tcDYvUIH7kuDb3MGK1FTZIOHzE/3Unnl2V+wFxvlyuKopz251Byg
YHcz6LODOXjK+GcW1epwB6RD9vIUXsVFboOLu6nCK1McU45EMzPK
VkWnJAgp1TIZcPcIroSwM7aTX+8tQKUT2+B5nSqXKIdySsHcBxVy
lxsCwcd5gvOXCsgQlB/o4PD650excGS1W6tnmxLO1Is8RgNRMiJr
qu0W21dVnZcur4OQPMsAJNzajUI4Y3G07XPm/dtGI1roRj8jDPbP
ZM5b8AlNJc6ZsAJA3ZsuKrtdwZEQ4UcEVdVUAoickuREN75/mzy9
+WkC/89+fX+Yg/ZceZeV5KLSrGFJDx6qOy5eQrIrBBRH2349o2yb
zYsqxsNFdBpGbYvlACsL0s0uS1D8zAARUUaqNjYaJSC5B2XERz/O
AXgiprwSgU9MGkAI4juIoiOGvZQWiKFPJ6eugj20xe+Nkq+MOBDB
sz7EN2Zd3Rnvlr2M1TVwH4SvpSSbaSe7xbNCT1GsKSAqvojc9Ep/
tPrVtFvHWm5DRvJBh58/bT/Pz1xDNE=<<<

I have bunch of mods enabled, biggest are Space Exploration, Krastorio 2, Rampant, Repair turret, Spidertron tiers and few more.

All settings related to this mod is in default:

Save game with your mod disabled for testing 
[SearchlightAssaultErrorOnload.zip](https://github.com/bolderbrush10/SearchlightAssault/files/9154843/SearchlightAssaultErrorOnload.zip)

**Comment by bolderbrush10** [comment]
Thanks for your report, it looks like this was a simple oversight on my part.

I have released version 2.2.3 which should fix this.
The new version should start to appear in the mod portal shortly.
If you don't see it in-game you can download it manually here: https://mods.factorio.com/mod/SearchlightAssault/downloads

**Comment by OndrejMus** [comment]
Hi, update is on portal and new map creation is working. Thank for update 👍
